server.port=9090
spring.application.name=api-gateway
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Route 1: Inventory Service (Secured Bouncer Active)
spring.cloud.gateway.routes[0].id=inventory-service
spring.cloud.gateway.routes[0].uri=lb://inventory-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# Route 2: Order Service (Secured Bouncer Active)
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# Route 3: Catalog Service (Secured Bouncer Active)
spring.cloud.gateway.routes[2].id=catalog-service
spring.cloud.gateway.routes[2].uri=lb://catalog-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# Route 4: Auth Service (Public Front Desk - NO FILTER ALLOWED)
spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=lb://auth-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/**

# ==========================================
# 🌐 CORS CONFIGURATION
# ==========================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*