server.port=8084
spring.application.name=inventory-service

spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Add this to your application.properties
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437